name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Slither Analyze
        uses: crytic/slither-action@v0.4.0
        with:
            fail-on: medium
            slither-args: --filter-paths "node_modules|contracts/mock" 